config/routes.rb
Rails.application.routes.draw do
  
  default_url_options :host => "localhost"
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, :controllers => { :omniauth_callbacks => "callbacks" }
  
  root 'home#index'
  
  resources :themes
  resources :user_confesses

end

app/models/theme.rb
class Theme < ActiveRecord::Base
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name, :text_color, :back_ground)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_for(@theme) do |f| %>
  <% if @theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% @theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text_color %><br>
    <%= f.text_field :text_color %>
  </div>
  <div class="field">
    <%= f.label :back_ground %><br>
    <%= f.text_field :back_ground %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form' %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Themes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Text color</th>
      <th>Back ground</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.name %></td>
        <td><%= theme.text_color %></td>
        <td><%= theme.back_ground %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form' %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theme.name %>
</p>

<p>
  <strong>Text color:</strong>
  <%= @theme.text_color %>
</p>

<p>
  <strong>Back ground:</strong>
  <%= @theme.back_ground %>
</p>

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>