config/routes.rb
Rails.application.routes.draw do
  
  default_url_options :host => "localhost"
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, :controllers => { :omniauth_callbacks => "callbacks" }
  
  root 'home#index'
  
  resources :themes
  resources :user_confesses

end

app/controllers/user_confesses_controller.rb
class UserConfessesController < ApplicationController
  before_action :set_user_confess, only: [:show, :edit, :update, :destroy]

  # GET /user_confesses
  # GET /user_confesses.json
  def index
    @user_confesses = UserConfess.all
  end

  # GET /user_confesses/1
  # GET /user_confesses/1.json
  def show
  end

  # GET /user_confesses/new
  def new
    @user_confess = UserConfess.new
  end

  # GET /user_confesses/1/edit
  def edit
  end

  # POST /user_confesses
  # POST /user_confesses.json
  def create
    @user_confess = UserConfess.new(user_confess_params)

    respond_to do |format|
      if @user_confess.save
        format.html { redirect_to @user_confess, notice: 'User confess was successfully created.' }
        format.json { render :show, status: :created, location: @user_confess }
      else
        format.html { render :new }
        format.json { render json: @user_confess.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_confesses/1
  # PATCH/PUT /user_confesses/1.json
  def update
    respond_to do |format|
      if @user_confess.update(user_confess_params)
        format.html { redirect_to @user_confess, notice: 'User confess was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_confess }
      else
        format.html { render :edit }
        format.json { render json: @user_confess.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_confesses/1
  # DELETE /user_confesses/1.json
  def destroy
    @user_confess.destroy
    respond_to do |format|
      format.html { redirect_to user_confesses_url, notice: 'User confess was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_confess
      @user_confess = UserConfess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_confess_params
      params.require(:user_confess).permit(:lover_name, :lover_sex, :cf_title, :cf_body)
    end
end

app/helpers/user_confesses_helper.rb
module UserConfessesHelper
end

app/views/user_confesses/_form.html.erb
<%= form_for(@user_confess) do |f| %>
  <% if @user_confess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_confess.errors.count, "error") %> prohibited this user_confess from being saved:</h2>

      <ul>
      <% @user_confess.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lover_name %><br>
    <%= f.text_field :lover_name %>
  </div>
  <div class="field">
    <%= f.label :lover_sex %><br>
    <%= f.text_field :lover_sex %>
  </div>
  <div class="field">
    <%= f.label :cf_title %><br>
    <%= f.text_field :cf_title %>
  </div>
  <div class="field">
    <%= f.label :cf_body %><br>
    <%= f.text_area :cf_body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_confesses/edit.html.erb
<h1>Editing User Confess</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_confess %> |
<%= link_to 'Back', user_confesses_path %>

app/views/user_confesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Confesses</h1>

<table>
  <thead>
    <tr>
      <th>Lover name</th>
      <th>Lover sex</th>
      <th>Cf title</th>
      <th>Cf body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_confesses.each do |user_confess| %>
      <tr>
        <td><%= user_confess.lover_name %></td>
        <td><%= user_confess.lover_sex %></td>
        <td><%= user_confess.cf_title %></td>
        <td><%= user_confess.cf_body %></td>
        <td><%= link_to 'Show', user_confess %></td>
        <td><%= link_to 'Edit', edit_user_confess_path(user_confess) %></td>
        <td><%= link_to 'Destroy', user_confess, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User confess', new_user_confess_path %>

app/views/user_confesses/new.html.erb
<h1>New User Confess</h1>

<%= render 'form' %>

<%= link_to 'Back', user_confesses_path %>

app/views/user_confesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lover name:</strong>
  <%= @user_confess.lover_name %>
</p>

<p>
  <strong>Lover sex:</strong>
  <%= @user_confess.lover_sex %>
</p>

<p>
  <strong>Cf title:</strong>
  <%= @user_confess.cf_title %>
</p>

<p>
  <strong>Cf body:</strong>
  <%= @user_confess.cf_body %>
</p>

<%= link_to 'Edit', edit_user_confess_path(@user_confess) %> |
<%= link_to 'Back', user_confesses_path %>